### ISSUE TITLE
Issue with Installation

### ISSUE THREAD

**Issue by jejjohnson** [secondmind-labs/markovflow#24]
I believe there is some inconsistency with the python version requirements in the `pyproject.toml` file. that prevents me from installing the package. 

**To Reproduce**
I do the `pip install` with a few options:
* Directly from pip `pip install markovflow`,
* Pip install from the tarball file
* Pip install from the cloned repo

---
**Error**

```bash
...
Collecting banded-matrices==0.0.6
  Using cached banded_matrices-0.0.6.tar.gz (63 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Package 'markovflow' requires a different Python: 3.7.0 not in '<3.8,>3.7'
```

**Note**: This is probably an issue on my end because I'm very surprised no other users have experienced this.

---
**Proposed Solution**

The `setup.py` file has the following requirements: `python_requires=">=3.7,<4.0",`. 

However, I believe the error is within the `pyproject.toml` file because it says `python = ">3.7,<3.8"` which is consistent with the error message. To confirm, I cloned the repo and changed this to `>=3.7,<3.8` and I didn't receive this error message. However, I received another error message which is related to the `banded_matrices` library installation (which is a different issue - see details below for more info).

<details>
(markovflow) [uvo53rl@jean-zay1: projects]$ git clone https://github.com/secondmind-labs/markovflow.git
Cloning into 'markovflow'...
remote: Enumerating objects: 1335, done.
remote: Counting objects: 100% (568/568), done.
remote: Compressing objects: 100% (252/252), done.
remote: Total 1335 (delta 347), reused 470 (delta 308), pack-reused 767
Receiving objects: 100% (1335/1335), 26.95 MiB | 23.02 MiB/s, done.
Resolving deltas: 100% (597/597), done.
(markovflow) [uvo53rl@jean-zay1: projects]$ cd markovflow/
(markovflow) [uvo53rl@jean-zay1: markovflow]$ pip install -e .
Obtaining file:///gpfsdswork/projects/rech/cli/uvo53rl/projects/markovflow

  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting banded-matrices==0.0.6
  Using cached banded_matrices-0.0.6.tar.gz (63 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scipy<2.0.0,>=1.4.1
  Using cached scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
Collecting setuptools<42.0.0,>=41.0.0
  Using cached setuptools-41.6.0-py2.py3-none-any.whl (582 kB)
Collecting gpflow<3.0,>=2.1
  Using cached gpflow-2.6.4-py3-none-any.whl (446 kB)
Collecting tensorflow-probability==0.11.0
  Using cached tensorflow_probability-0.11.0-py2.py3-none-any.whl (4.3 MB)
Collecting importlib_metadata<2.0,>=1.6
  Using cached importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
Collecting numpy<2.0.0,>=1.18.0
  Using cached numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting tensorflow>2.2.0
  Using cached tensorflow-2.11.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (588.3 MB)
Collecting google-auth<2.0.0,>=1.16.0
  Using cached google_auth-1.35.0-py2.py3-none-any.whl (152 kB)
ERROR: Package 'markovflow' requires a different Python: 3.7.0 not in '<3.8,>3.7'
(markovflow) [uvo53rl@jean-zay1: markovflow]$
(markovflow) [uvo53rl@jean-zay1: markovflow]$ nano pyproject.toml
(markovflow) [uvo53rl@jean-zay1: markovflow]$ pip install -e .
Obtaining file:///gpfsdswork/projects/rech/cli/uvo53rl/projects/markovflow
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting banded-matrices==0.0.6
  Using cached banded_matrices-0.0.6.tar.gz (63 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting importlib_metadata<2.0,>=1.6
  Using cached importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
Collecting google-auth<2.0.0,>=1.16.0
  Using cached google_auth-1.35.0-py2.py3-none-any.whl (152 kB)
Collecting tensorflow-probability==0.11.0
  Using cached tensorflow_probability-0.11.0-py2.py3-none-any.whl (4.3 MB)
Collecting numpy<2.0.0,>=1.18.0
  Using cached numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting scipy<2.0.0,>=1.4.1
  Using cached scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
Collecting gpflow<3.0,>=2.1
  Using cached gpflow-2.6.4-py3-none-any.whl (446 kB)
Collecting setuptools<42.0.0,>=41.0.0
  Using cached setuptools-41.6.0-py2.py3-none-any.whl (582 kB)
Collecting tensorflow>2.2.0
  Using cached tensorflow-2.11.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (588.3 MB)
Collecting cmake<3.19.0,>=3.18.0
  Using cached cmake-3.18.4.post1-py3-none-manylinux1_x86_64.whl (17.7 MB)
Collecting tensorflow>2.2.0
  Using cached tensorflow-2.4.4-cp37-cp37m-manylinux2010_x86_64.whl (394.5 MB)
Collecting dm-tree
  Downloading dm_tree-0.1.7-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.3/143.3 kB 18.6 MB/s eta 0:00:00
Collecting decorator
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting cloudpickle==1.3
  Downloading cloudpickle-1.3.0-py2.py3-none-any.whl (26 kB)
Collecting gast>=0.3.2
  Downloading gast-0.5.3-py3-none-any.whl (19 kB)
Collecting six>=1.10.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.2.4-py3-none-any.whl (10 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting lark>=1.1.0
  Downloading lark-1.1.4-py3-none-any.whl (107 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.8/107.8 kB 34.7 MB/s eta 0:00:00
Collecting multipledispatch>=0.6
  Downloading multipledispatch-0.6.0-py3-none-any.whl (11 kB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting gpflow<3.0,>=2.1
  Downloading gpflow-2.6.3-py3-none-any.whl (445 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 445.3/445.3 kB 77.5 MB/s eta 0:00:00
  Downloading gpflow-2.6.2-py3-none-any.whl (445 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 445.2/445.2 kB 72.9 MB/s eta 0:00:00
  Downloading gpflow-2.6.1-py3-none-any.whl (444 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 444.6/444.6 kB 91.0 MB/s eta 0:00:00
  Downloading gpflow-2.6.0-py3-none-any.whl (443 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 443.5/443.5 kB 33.5 MB/s eta 0:00:00
  Downloading gpflow-2.5.2-py3-none-any.whl (383 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.9/383.9 kB 69.5 MB/s eta 0:00:00
  Downloading gpflow-2.5.1-py3-none-any.whl (381 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.9/381.9 kB 75.0 MB/s eta 0:00:00
  Downloading gpflow-2.4.0-py3-none-any.whl (334 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 334.0/334.0 kB 47.5 MB/s eta 0:00:00
Collecting tabulate
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting deprecated
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting zipp>=0.5
  Using cached zipp-3.11.0-py3-none-any.whl (6.6 kB)
Collecting numpy<2.0.0,>=1.18.0
  Using cached numpy-1.19.5-cp37-cp37m-manylinux2010_x86_64.whl (14.8 MB)
Collecting tensorboard~=2.4
  Using cached tensorboard-2.11.0-py3-none-any.whl (6.0 MB)
Collecting google-pasta~=0.2
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting six>=1.10.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting typing-extensions
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting tensorflow-estimator<2.5.0,>=2.4.0
  Using cached tensorflow_estimator-2.4.0-py2.py3-none-any.whl (462 kB)
Requirement already satisfied: wheel~=0.35 in /gpfsssd/scratch/rech/cli/uvo53rl/miniconda3/envs/markovflow/lib/python3.7/site-packages (from tensorflow>2.2.0->markovflow==0.0.12) (0.37.1)
Collecting wrapt~=1.12.1
  Using cached wrapt-1.12.1-cp37-cp37m-linux_x86_64.whl
Collecting grpcio~=1.32.0
  Using cached grpcio-1.32.0-cp37-cp37m-manylinux2014_x86_64.whl (3.8 MB)
Collecting h5py~=2.10.0
  Using cached h5py-2.10.0-cp37-cp37m-manylinux1_x86_64.whl (2.9 MB)
Collecting termcolor~=1.1.0
  Using cached termcolor-1.1.0-py3-none-any.whl
Collecting absl-py~=0.10
  Using cached absl_py-0.15.0-py3-none-any.whl (132 kB)
Collecting gast>=0.3.2
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
Collecting opt-einsum~=3.3.0
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting protobuf>=3.9.2
  Using cached protobuf-4.21.10-cp37-abi3-manylinux2014_x86_64.whl (408 kB)
Collecting keras-preprocessing~=1.1.2
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting flatbuffers~=1.12.0
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting astunparse~=1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting werkzeug>=1.0.1
  Using cached Werkzeug-2.2.2-py3-none-any.whl (232 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)
Collecting protobuf>=3.9.2
  Using cached protobuf-3.20.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
Collecting requests<3,>=2.21.0
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.4-py3-none-any.whl (93 kB)
  Using cached Markdown-3.3.7-py3-none-any.whl (97 kB)
  Using cached Markdown-3.3.6-py3-none-any.whl (97 kB)
  Using cached Markdown-3.3.4-py3-none-any.whl (97 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Requirement already satisfied: certifi>=2017.4.17 in /gpfsssd/scratch/rech/cli/uvo53rl/miniconda3/envs/markovflow/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow>2.2.0->markovflow==0.0.12) (2022.9.24)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
Collecting MarkupSafe>=2.1.1
  Using cached MarkupSafe-2.1.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Building wheels for collected packages: banded-matrices
  Building wheel for banded-matrices (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for banded-matrices (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [201 lines of output]
      A setup.py file already exists. Using it.
      running build
      running build_py
      creating /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build
      creating /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37
      creating /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices
      copying banded_matrices/__init__.py -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices
      copying banded_matrices/banded.py -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices
      copying banded_matrices/library.py -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices
      copying banded_matrices/platform.py -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices
      copying banded_matrices/types.py -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices
      running egg_info
      creating banded_matrices.egg-info
      writing banded_matrices.egg-info/PKG-INFO
      writing dependency_links to banded_matrices.egg-info/dependency_links.txt
      writing requirements to banded_matrices.egg-info/requires.txt
      writing top-level names to banded_matrices.egg-info/top_level.txt
      writing manifest file 'banded_matrices.egg-info/SOURCES.txt'
      reading manifest file 'banded_matrices.egg-info/SOURCES.txt'
      writing manifest file 'banded_matrices.egg-info/SOURCES.txt'
      copying banded_matrices/CMakeLists.txt -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices
      creating /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc
      copying banded_matrices/cc/CMakeLists.txt -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc
      creating /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/include
      creating /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/include/banded_matrices
      copying banded_matrices/cc/include/banded_matrices/banded_matrix.hpp -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/include/banded_matrices
      copying banded_matrices/cc/include/banded_matrices/cholesky.hpp -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/include/banded_matrices
      copying banded_matrices/cc/include/banded_matrices/common.hpp -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/include/banded_matrices
      copying banded_matrices/cc/include/banded_matrices/product.hpp -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/include/banded_matrices
      copying banded_matrices/cc/include/banded_matrices/solve.hpp -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/include/banded_matrices
      copying banded_matrices/cc/include/banded_matrices/unary_broadcastable_op_kernel.hpp -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/include/banded_matrices
      creating /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src
      creating /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      copying banded_matrices/cc/src/banded_matrices/block_band.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      copying banded_matrices/cc/src/banded_matrices/cholesky.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      copying banded_matrices/cc/src/banded_matrices/inverse.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      copying banded_matrices/cc/src/banded_matrices/outer_vec_vec.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      copying banded_matrices/cc/src/banded_matrices/pack_matrix.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      copying banded_matrices/cc/src/banded_matrices/product_band_band.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      copying banded_matrices/cc/src/banded_matrices/product_band_mat.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      copying banded_matrices/cc/src/banded_matrices/reverse_inverse.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      copying banded_matrices/cc/src/banded_matrices/solve_triang_band.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      copying banded_matrices/cc/src/banded_matrices/solve_triang_mat.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      copying banded_matrices/cc/src/banded_matrices/square_band.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      copying banded_matrices/cc/src/banded_matrices/symmetrise.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      copying banded_matrices/cc/src/banded_matrices/transpose_band.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/src/banded_matrices
      creating /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/test
      copying banded_matrices/cc/test/common.hpp -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/test
      copying banded_matrices/cc/test/main.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/test
      copying banded_matrices/cc/test/test_banded_matrix.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/test
      copying banded_matrices/cc/test/test_product_band_band.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/test
      copying banded_matrices/cc/test/test_solve.cc -> /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/cc/test
      running build_ext
      cmake /tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/banded_matrices -Wno-dev -DPYTHON_BIN=/gpfsscratch/rech/cli/uvo53rl/miniconda3/envs/markovflow/bin/python -DCMAKE_BUILD_TYPE=release -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/lib -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/lib.linux-x86_64-cpython-37/banded_matrices/bin -DCMAKE_VERBOSE_MAKEFILE:BOOL=on
      -- The C compiler identification is GNU 8.4.1
      -- The CXX compiler identification is unknown
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      CMake Error at CMakeLists.txt:17 (project):
        The CMAKE_CXX_COMPILER:

          g++-7

        is not a full path and was not found in the PATH.

        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.

      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/temp.linux-x86_64-cpython-37/CMakeFiles/CMakeOutput.log".
      See also "/tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build/temp.linux-x86_64-cpython-37/CMakeFiles/CMakeError.log".
      /tmp/pip-build-env-z3dhjd43/overlay/lib/python3.7/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'banded_matrices.cc' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'banded_matrices.cc' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'banded_matrices.cc' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'banded_matrices.cc' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      /tmp/pip-build-env-z3dhjd43/overlay/lib/python3.7/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'banded_matrices.cc.include.banded_matrices' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'banded_matrices.cc.include.banded_matrices' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'banded_matrices.cc.include.banded_matrices' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'banded_matrices.cc.include.banded_matrices' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      /tmp/pip-build-env-z3dhjd43/overlay/lib/python3.7/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'banded_matrices.cc.src.banded_matrices' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'banded_matrices.cc.src.banded_matrices' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'banded_matrices.cc.src.banded_matrices' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'banded_matrices.cc.src.banded_matrices' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      /tmp/pip-build-env-z3dhjd43/overlay/lib/python3.7/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'banded_matrices.cc.test' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'banded_matrices.cc.test' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'banded_matrices.cc.test' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'banded_matrices.cc.test' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      error: command '/tmp/pip-build-env-z3dhjd43/overlay/bin/cmake' failed with exit code 1
      Traceback (most recent call last):
        File "/gpfsscratch/rech/cli/uvo53rl/miniconda3/envs/markovflow/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/gpfsscratch/rech/cli/uvo53rl/miniconda3/envs/markovflow/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/gpfsscratch/rech/cli/uvo53rl/miniconda3/envs/markovflow/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
          metadata_directory)
        File "/tmp/pip-build-env-z3dhjd43/overlay/lib/python3.7/site-packages/poetry/core/masonry/api.py", line 67, in build_wheel
          return WheelBuilder.make_in(poetry, Path(wheel_directory))
        File "/tmp/pip-build-env-z3dhjd43/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 80, in make_in
          wb.build(target_dir=directory)
        File "/tmp/pip-build-env-z3dhjd43/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 114, in build
          self._build(zip_file)
        File "/tmp/pip-build-env-z3dhjd43/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 168, in _build
          self._run_build_command(setup)
        File "/tmp/pip-build-env-z3dhjd43/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 212, in _run_build_command
          str(self._path / "build"),
        File "/gpfsscratch/rech/cli/uvo53rl/miniconda3/envs/markovflow/lib/python3.7/subprocess.py", line 328, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/gpfsscratch/rech/cli/uvo53rl/miniconda3/envs/markovflow/bin/python', '/tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/setup.py', 'build', '-b', '/tmp/pip-install-53c0n0oi/banded-matrices_2fdeb4f02f09479eb65cfa50867bc5f7/build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for banded-matrices
Failed to build banded-matrices
ERROR: Could not build wheels for banded-matrices, which is required to install pyproject.toml-based projects
</details>

---

**System information**
 - OS: macOS, Linux
 - Python version: 3.7, 3.8, 3.10
 - Markovflow version: 0.0.1, 0.0.13
 - TensorFlow version: N/A
 - GPflow version: N/A

**Additional context**

**Comment by vincentadam87** [comment]
Hi,

with delay, thanks for pointing this out.
I will update the requirements

Re banded_matrices:
It seems you have a compilation error.
I had a similar problem once, when I changed linux, distribution.
I was missing some core c++ packages
I suggest you check the file
https://github.com/secondmind-labs/banded_matrices/blob/master/.github/workflows/quality-check.yaml
which describes the instructions to build it on the github servers.

Let me know if the problem persists.

**Comment by vincentadam87** [comment]
fixed in #25 
leaving open while banded_matrices problem is not fixed
